shelves:
  - id: "57a5fe24-f280-4897-ba9d-4177a6174748"
    lock_pin: 17
    door_pin: 27

  - id: shelf_2
    lock_pin: 22
    door_pin: 23

  - id: shelf_3
    lock_pin: 24
    door_pin: 25
